version: "3.9"
services:
  database:
    ports:
      - "5433:5432"
    container_name: postgres_con
    image: postgres
    environment:
      - POSTGRES_DB=database
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    restart: unless-stopped
  backend:
    build: .
    container_name: kurstans_app
    ports:
      - "2020:2020"
    environment:
      POSTGRES_DB: jdbc:postgresql://database:5432/test
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    depends_on:
      - database
    restart: unless-stopped